import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faBeer, faCoffee, faFaceAngry, faMoon, faStar} from '@fortawesome/free-solid-svg-icons'
import { montserrat } from './fonts'
import './global.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import React from 'react'
import { brands } from '@fortawesome/fontawesome-svg-core/import.macro'

const current_year = new Date().getFullYear();
const inter= Inter({subsets:['latin']})

export const metadata={
  tittle: 'Next.js 14.0.4 Metadata - Icons',
  description: 'Generated by create next app',
  icons: {
    icon: [
      '/code.png',
    ],
    apple:[
      '/lol.png',
    ],
    shortcut:[
      '/png.png',
    ],
  },
  manifest: '/png.png'
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased`}>
       
        <h1 className='flex justify-center'>Este título</h1>
        
        <div style={{border: '1px solid #289488 '}}>
        {children}
        </div>

        <div className="bg-[#fbe2e3] absolute top-[-6rem] -z-10 right-[11rem] h-[31.25rem] w-[31.25rem] rounded-full blur-[10rem] sm:w-[68.75rem] dark:bg-[#946263]"></div>
        <div className="bg-[#dbd7fb] absolute top-[-1rem] -z-10 left-[-35rem] h-[31.25rem] w-[50rem] rounded-full blur-[10rem] sm:w-[68.75rem] md:left-[-33rem] lg:left-[-28rem] xl:left-[-15rem] 2xl:left-[-5rem] dark:bg-[#676394]"></div>
        
        <div>
              <Link href="https://www.facebook.com/edison.thomasguillen/" target="_blank" className=' items-center flex justify-center'>
              <FontAwesomeIcon icon={faMoon} width={50} height={50}/> 
              </Link>
              <p className='flex justify-center'>Copyright © {current_year}, 1ManStartup LLC. All Rights Reserved.</p>
        </div>
        </body>


    </html>
    


    
  )

            }
  

